### ISSUE TITLE
Timegap between registering passport an receiving ubi

### ISSUE THREAD

**Issue by ubiubi18** [rgex/UBIC-android-wallet#12]
If you register a new passport, your ubic-app needs 4-8 Minutes to process that transaction and meanwhile behaves as if nothing did happen at all.
 
Some new members may confuse that with a broken app and reinstall or abandon ubic at all as buggy - most might not have the patience to revisit the app 8-10 minutes later. 

So maybe there should be a message like "your transaction is beeing processed, that may take a few minutes" or similar to avoid confusion until you are registered and receive your ubi.

**Comment by ubiubi18** [comment]
So i guess the app needs to wait for another block until it is able to send the register transacrion, and another block to receive the confirmation that you get ubi, so it is allways 5-9 minutes waiting,  right?

**Comment by rgex** [comment]
That's correct, I will add support to show pending transactions and create show that the UBI subscription is pending.

**Comment by ubiubi18** [comment]
![20190625_180130](https://user-images.githubusercontent.com/39676643/60114143-7dda4300-9773-11e9-8c9a-de0de743756e.jpg)
To clarify: the "100%" of "reading the passport is in progress" - right after NFC-reading is finished - is overlapping the "Done! in some minutes you should start receiving your UBI" - text on my mobile (samsung galaxy s7) if i go on "Balance" or "My UBI" afterwards, there should be a message like "Done! in some minutes you should start receiving your UBI" as well to avoid confusion?

**Comment by ubiubi18** [comment]
![20190625_181124](https://user-images.githubusercontent.com/39676643/60115047-54221b80-9775-11e9-8544-06547694952c.jpg)
![Uploading 20190625_181141.jpg…]()
![Uploading 20190625_181331.jpg…]()
I intend to edit another tutorial in early August, right now i lack of time...
