### ISSUE TITLE
New countries

### ISSUE THREAD

**Issue by kseistrup** [rgex/UBIC-android-wallet#17]
Now that [UBIC core](https://github.com/UBIC-repo/core/releases/tag/V0.5.0) supports Denmark, Israel, the Netherlands, Poland, Portugal, Romania, Russia and Turkey, will the android wallet need an update?

**Comment by rgex** [comment]
Yes, it will happen.
I expect it to be available next week.

**Comment by rgex** [comment]
@kseistrup Denmark should work now, if doesn't, please report it as a bug ;)

**Comment by kseistrup** [comment]
🇩🇰 works now — thanks!
