### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [rgex/UBIC-android-wallet#20]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 103 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on UBIC-android-wallet (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve UBIC-android-wallet's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by misterAnderson90** [comment]
Hello, @ubiubi18 

Do you want to receive the report with these warnings? Otherwise, should I close this issue?

**Comment by ubiubi18** [comment]
I am not involved at all. i guess this project was discontiued like more than a year ago anyway?

**Comment by misterAnderson90** [comment]
Thanks for your response. Since the project has been discontinued, I'm closing this issue.
