### ISSUE TITLE
Error when submitting

### ISSUE THREAD

**Issue by philipp** [rgex/UBIC-android-wallet#4]
Installed [app](https://play.google.com/store/apps/details?id=network.ubic.ubic) from Google Play Store. (version 1.1)
Tried scanning my passport (US)
Scan seems to work fine, but I get an error message when it tries to send to the server.
Unclear if the problem is in the app or on the server, but submitting here, in case things are out of sync or it's a known issue.

No obvious way of getting log info or better error diagnostics, without hooking up to adb or something.
Which I'm willing to do if it would help.
But I'll wait for a response here, first, since I'm not set up for that right now.

**Comment by rgex** [comment]
Thank you for reporting the bug.
I took a look at the logs and it is a UBIC core problem.
When was your passport issued (month and year)?

**Comment by philipp** [comment]
Issued in August of 2018.
About 2 weeks ago.

**Comment by ubiubi18** [comment]
maybe your document signing certificate is so fresh that it is not known to UBIC yet? It seems like ubicorn updated the known Document Signing Certificates meanwhile.

**Comment by ubicorn** [comment]
Indeed, I imported a new batch of Document Signing Certificates, @philipp try again to see if it works now.

**Comment by philipp** [comment]
Yes, looking at the details via the [ReadID](https://play.google.com/store/apps/details?id=nl.innovalor.nfciddocshowcase) app, it looks like the Document Signing Certificate is valid starting from 2018-06-20

And now that I tried again, it succeeded.  And now I see a >10% increase in the number of unique users! :-)  Nice!

So is this level of maintenance likely to be a challenge in the future?
Different government agencies updating certs at unpredictable times?

**Comment by philipp** [comment]
Anyway, this would then be an UBIC-core issue.
Closing this item.

**Comment by ubicorn** [comment]
I am doing one CSCA/DSC import from the ICAO Public key Directory every month. However I have noticed that DSCs are often published up to three months after they were issued.
One solution that is already halfway implemented in the core is to extract the DSC from the passport and send it to the network.
This would still be secured because the DSC is signed by the CSCA, sending a forged DSC will not work.
I will add a note mentioning this issue in the documentation.
