### ISSUE TITLE
Can't Restore My Wallet

### ISSUE THREAD

**Issue by A-Lonely-Onion** [rgex/UBIC-android-wallet#8]
I registered my passport to my wallet, then I deleted the app on accident, installed it  again and tried registering my passport again and I got an error, the error I get says invalid sever response

**Comment by rgex** [comment]
I am sorry to hear it.
Once the App is deleted the private key is lost (It can be exported in the my private key tab if you want to uninstall the app and have a backup).
It might be possible to gain access to the wallet in the future with your passport, but there are no guarantees it will be implemented.

**Comment by A-Lonely-Onion** [comment]
I have the private key is it possible to resort it that way

**Comment by rgex** [comment]
If you have the private key from before you deleted the App then you are fine.
I can add a functionality to the app so you can import a private key

**Comment by A-Lonely-Onion** [comment]
Yes I do have the private key before I deleted the app, that would be
amazing feature to have, I'm pretty sure it'll help many that made the same
mistake as me

**Comment by rgex** [comment]
Hi, the latest version supports the private key import, you can download it from the play stor: https://play.google.com/store/apps/details?id=network.ubic.ubic
